/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PaintingInfo = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'image' : ExternalBlob,
  'priceUSD' : IDL.Float64,
  'dimensions' : IDL.Text,
  'material' : IDL.Text,
});
export const Painting = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'image' : ExternalBlob,
  'priceUSD' : IDL.Float64,
  'dimensions' : IDL.Text,
  'material' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addPainting' : IDL.Func([PaintingInfo], [IDL.Nat], []),
  'deletePainting' : IDL.Func([IDL.Nat], [], []),
  'getAllPaintings' : IDL.Func([], [IDL.Vec(Painting)], ['query']),
  'getPainting' : IDL.Func([IDL.Nat], [Painting], ['query']),
  'updatePainting' : IDL.Func([IDL.Nat, PaintingInfo], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PaintingInfo = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'image' : ExternalBlob,
    'priceUSD' : IDL.Float64,
    'dimensions' : IDL.Text,
    'material' : IDL.Text,
  });
  const Painting = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'image' : ExternalBlob,
    'priceUSD' : IDL.Float64,
    'dimensions' : IDL.Text,
    'material' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addPainting' : IDL.Func([PaintingInfo], [IDL.Nat], []),
    'deletePainting' : IDL.Func([IDL.Nat], [], []),
    'getAllPaintings' : IDL.Func([], [IDL.Vec(Painting)], ['query']),
    'getPainting' : IDL.Func([IDL.Nat], [Painting], ['query']),
    'updatePainting' : IDL.Func([IDL.Nat, PaintingInfo], [], []),
  });
};

export const init = ({ IDL }) => { return []; };